import type { Metadata } from "next"
import Link from "next/link"
import { MainNav } from "@/components/navigation/main-nav"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for ChefMate AI Recipe Generator. Read our terms and conditions for using our recipe generation service.",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background pb-20 md:pb-0">
      <MainNav />

      <main id="main-content" className="container mx-auto px-4 py-8 max-w-4xl">
        <Card>
          <CardHeader>
            <CardTitle className="text-3xl font-bold">Terms of Service</CardTitle>
            <p className="text-muted-foreground">Last Updated: November 13, 2025</p>
          </CardHeader>
          <CardContent className="prose dark:prose-invert max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By accessing and using ChefMate (&quot;the Service&quot;), you accept and agree to be bound by the terms
                and provision of this agreement. If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground mb-3">
                ChefMate is an AI-powered recipe generation service that:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Generates personalized recipes based on user-provided ingredients</li>
                <li>Respects dietary restrictions and allergies as specified by users</li>
                <li>Provides nutritional information as estimates</li>
                <li>Allows users to save and organize recipes locally in their browser</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">3. User Responsibilities</h2>
              <p className="text-muted-foreground mb-3">
                You agree to:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Provide accurate information about dietary restrictions and allergies</li>
                <li>Verify the safety and suitability of generated recipes before cooking</li>
                <li>Not use the Service for any illegal or unauthorized purpose</li>
                <li>Not attempt to circumvent any rate limiting or access controls</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">4. Recipe Accuracy and Safety</h2>
              <p className="text-muted-foreground mb-3">
                <strong>Important Notice:</strong> While ChefMate uses advanced AI to generate recipes,
                we cannot guarantee:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>The complete accuracy of nutritional information</li>
                <li>The suitability of recipes for specific dietary needs or allergies</li>
                <li>The success or taste of the final dish</li>
              </ul>
              <p className="text-muted-foreground mt-3">
                Users are responsible for reviewing recipes and ensuring they meet their dietary requirements
                before preparation. Consult healthcare professionals for specific dietary advice.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
              <p className="text-muted-foreground mb-3">
                The recipes generated by ChefMate are provided for personal, non-commercial use. You may:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Use generated recipes for personal cooking</li>
                <li>Share recipes with friends and family</li>
                <li>Print recipes for personal use</li>
              </ul>
              <p className="text-muted-foreground mt-3">
                The ChefMate platform, logo, and interface are protected by copyright and trademark laws.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">6. Privacy and Data</h2>
              <p className="text-muted-foreground">
                Your recipe data is stored locally in your browser. We do not collect or store your personal
                recipes on our servers. For more information, please review our{" "}
                <Link href="/privacy" className="text-primary hover:underline">
                  Privacy Policy
                </Link>.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">7. Service Limitations</h2>
              <p className="text-muted-foreground mb-3">
                ChefMate may implement rate limits to ensure fair usage:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Recipe generation may be limited to a certain number per hour</li>
                <li>The Service may be temporarily unavailable for maintenance</li>
                <li>We reserve the right to modify or discontinue features with notice</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">8. Disclaimer of Warranties</h2>
              <p className="text-muted-foreground">
                The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either
                express or implied, including but not limited to warranties of merchantability, fitness for
                a particular purpose, or non-infringement.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">9. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                ChefMate shall not be liable for any indirect, incidental, special, consequential, or punitive
                damages resulting from your use or inability to use the Service, including but not limited to
                food allergies, dietary complications, or cooking mishaps.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">10. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify these terms at any time. Changes will be effective immediately
                upon posting to the Service. Your continued use of the Service following the posting of changes
                constitutes acceptance of those changes.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">11. Contact Information</h2>
              <p className="text-muted-foreground">
                For questions about these Terms of Service, please contact us at{" "}
                <Link href="/contact" className="text-primary hover:underline">
                  our contact page
                </Link>.
              </p>
            </section>

            <div className="mt-12 p-6 bg-muted rounded-lg">
              <p className="text-sm text-muted-foreground">
                By using ChefMate, you acknowledge that you have read, understood, and agree to be bound by
                these Terms of Service.
              </p>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
